CRITICAL - 2021-08-24 01:03:13 --> Call to undefined method App\Controllers\Apilogin::response()
#0 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(928): App\Controllers\Apilogin->Login()
#1 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apilogin))
#2 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/LabustaCI/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 /opt/lampp/htdocs/LabustaCI/system/Commands/Server/rewrite.php(45): require_once('/opt/lampp/htdo...')
#5 {main}
CRITICAL - 2021-08-24 01:03:33 --> Object of class App\Models\LoginModel could not be converted to string
#0 /opt/lampp/htdocs/LabustaCI/app/Controllers/Apilogin.php(54): CodeIgniter\Debug\Exceptions->errorHandler(4096, 'Object of class...', '/opt/lampp/htdo...', 54, Array)
#1 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(928): App\Controllers\Apilogin->Login()
#2 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apilogin))
#3 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /opt/lampp/htdocs/LabustaCI/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /opt/lampp/htdocs/LabustaCI/system/Commands/Server/rewrite.php(45): require_once('/opt/lampp/htdo...')
#6 {main}
CRITICAL - 2021-08-24 01:08:29 --> Undefined variable: model
#0 /opt/lampp/htdocs/LabustaCI/app/Controllers/Apilogin.php(51): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', '/opt/lampp/htdo...', 51, Array)
#1 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(928): App\Controllers\Apilogin->Login()
#2 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apilogin))
#3 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /opt/lampp/htdocs/LabustaCI/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /opt/lampp/htdocs/LabustaCI/system/Commands/Server/rewrite.php(45): require_once('/opt/lampp/htdo...')
#6 {main}
CRITICAL - 2021-08-24 01:13:26 --> Undefined variable: response
#0 /opt/lampp/htdocs/LabustaCI/app/Controllers/Apilogin.php(41): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', '/opt/lampp/htdo...', 41, Array)
#1 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(928): App\Controllers\Apilogin->Login()
#2 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apilogin))
#3 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /opt/lampp/htdocs/LabustaCI/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /opt/lampp/htdocs/LabustaCI/system/Commands/Server/rewrite.php(45): require_once('/opt/lampp/htdo...')
#6 {main}
CRITICAL - 2021-08-24 01:15:39 --> Argument 2 passed to CodeIgniter\RESTful\ResourceController::respond() must be of the type int or null, array given, called in /opt/lampp/htdocs/LabustaCI/app/Controllers/Apilogin.php on line 53
#0 /opt/lampp/htdocs/LabustaCI/app/Controllers/Apilogin.php(53): CodeIgniter\RESTful\ResourceController->respond(Array, Array, 200)
#1 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(928): App\Controllers\Apilogin->Login()
#2 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apilogin))
#3 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /opt/lampp/htdocs/LabustaCI/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /opt/lampp/htdocs/LabustaCI/system/Commands/Server/rewrite.php(45): require_once('/opt/lampp/htdo...')
#6 {main}
CRITICAL - 2021-08-24 01:16:21 --> syntax error, unexpected ';', expecting ']'
#0 /opt/lampp/htdocs/LabustaCI/system/Router/Router.php(169): CodeIgniter\Router\Router->autoRoute('Apilogin/Login')
#1 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(809): CodeIgniter\Router\Router->handle('Apilogin/Login')
#2 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /opt/lampp/htdocs/LabustaCI/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /opt/lampp/htdocs/LabustaCI/system/Commands/Server/rewrite.php(45): require_once('/opt/lampp/htdo...')
#6 {main}
ERROR - 2021-08-24 23:03:04 --> Error connecting to the database: Connection refused
CRITICAL - 2021-08-24 23:03:04 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
#0 /opt/lampp/htdocs/LabustaCI/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /opt/lampp/htdocs/LabustaCI/system/Database/BaseBuilder.php(2049): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /opt/lampp/htdocs/LabustaCI/app/Controllers/Auth.php(23): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(928): App\Controllers\Auth->loginProses()
#4 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/LabustaCI/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 /opt/lampp/htdocs/LabustaCI/system/Commands/Server/rewrite.php(45): require_once('/opt/lampp/htdo...')
#8 {main}
CRITICAL - 2021-08-24 23:03:04 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /opt/lampp/htdocs/LabustaCI/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/opt/lampp/htdo...', 99, Array)
#1 /opt/lampp/htdocs/LabustaCI/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Auth), true)
#2 /opt/lampp/htdocs/LabustaCI/system/Debug/Exceptions.php(278): include('/opt/lampp/htdo...')
#3 /opt/lampp/htdocs/LabustaCI/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-08-24 23:03:17 --> Undefined index: nomor_induk
#0 /opt/lampp/htdocs/LabustaCI/app/Controllers/Auth.php(23): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', '/opt/lampp/htdo...', 23, Array)
#1 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(928): App\Controllers\Auth->loginProses()
#2 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 /opt/lampp/htdocs/LabustaCI/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /opt/lampp/htdocs/LabustaCI/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /opt/lampp/htdocs/LabustaCI/system/Commands/Server/rewrite.php(45): require_once('/opt/lampp/htdo...')
#6 {main}
